### ISSUE TITLE
SQL Injection in qldb public Node Pickup

### ISSUE THREAD

**Issue by Javantea** [awgh/ratnet#1]
String concatenation is not a safe way to add strings that are user controllable to an SQL statement. It shouldn't be used even if the strings have been filtered.
https://github.com/awgh/ratnet/blob/master/nodes/qldb/public.go#L80

**Comment by awgh** [comment]
Yup, good spot.  We removed the filter in this function that restricted channel names to only alphanums, but neglected to add a suitable escape.  The string concatenation is not avoidable here because of a bug in QL (or rather a non-implemented feature).

**Comment by awgh** [comment]
Fixed issue by restoring the old filter code.  I agree string concatenation is not ideal, but QL is not a fully implemented SQL in certain ways.  A node written on a better DB could use inner joins and prepared statements for comma separated IN clauses, but there's a bug with the way database/sql talks to QL.  QL is purego where SQLite isn't, which is the only reason to have a QL implementation.

https://github.com/awgh/ratnet/commit/02aa06d66b5b57d035e04fea598a31a2fa9a4ebe
